absl-py==1.2.0
einops==0.4.1
h5py==3.7.0
keopscore==2.1
opt-einsum==3.3.0
pandas==1.4.2 
pytorch-wavelet 
PyWavelets==1.4.1
scikit-image==0.19.3
scikit-learn==1.0.2
scipy==1.7.3
statsmodels==0.13.2
sympy==1.11.1
torch==1.9.0
EMD-signal==1.5.1
setuptools==59.5.0
yaml==6.0.1
transformers==4.11.3
matplotlib==3.7.1
tensorboard==2.14.0
